import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        soc: {
          bg: "var(--soc-bg)",
          surface: "var(--soc-surface)",
          surface2: "var(--soc-surface2)",
          surface3: "var(--soc-surface3)",
          border: "var(--soc-border)",
          "border-strong": "var(--soc-border-strong)",
          text: "var(--soc-text)",
          "text-secondary": "var(--soc-text-secondary)",
          "text-tertiary": "var(--soc-text-tertiary)",
          "text-quaternary": "var(--soc-text-quaternary)",
          red: "var(--soc-red)",
          "red-muted": "var(--soc-red-muted)",
          "red-border": "var(--soc-red-border)",
          amber: "var(--soc-amber)",
          "amber-muted": "var(--soc-amber-muted)",
          "amber-border": "var(--soc-amber-border)",
          green: "var(--soc-green)",
          "green-muted": "var(--soc-green-muted)",
          "green-border": "var(--soc-green-border)",
          blue: "var(--soc-blue)",
          "blue-muted": "var(--soc-blue-muted)",
          "blue-border": "var(--soc-blue-border)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-up": "fade-up 0.4s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "pulse-glow": "pulse-glow 2s infinite",
        "cursor-blink": "cursor-blink 1s infinite steps(1)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-up": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-in-right": { from: { opacity: "0", transform: "translateX(12px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "pulse-glow": { "0%, 100%": { boxShadow: "0 0 0 0 rgba(59, 130, 246, 0.4)" }, "50%": { boxShadow: "0 0 0 4px rgba(59, 130, 246, 0)" } },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
